src/pagalotodo-ucab-web/Models/AllServicesViewModel.cs
namespace UCABPagaloTodoWeb.Models
{
    public class AllServicesViewModel
    {
        public Guid ServiceId { get; set; }
        public string? ServiceName { get; set; }
        public string? ContactNumber { get; set; }
        public string? TypeService { get; set; }
        public string? ProviderUsername { get; set; }
        public string? CompanyName { get; set; }
    }
}

src/pagalotodo-ucab-web/Models/AllUsersViewModel.cs
namespace UCABPagaloTodoWeb.Models
{
    public class AllUsersViewModel
    {
        public string? Dni { get; set; }
        public string? Name { get; set; }
        public string? Lastname { get; set; }
        public string? Username { get; set; }
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
    }
}

src/pagalotodo-ucab-web/Models/ChangeUserStatusViewModel.cs
namespace UCABPagaloTodoWeb.Models
{
    public class ChangeUserStatusViewModel
    {
        public string? Username { get; set; }
        public bool? Status { get; set; }
    }
}

src/pagalotodo-ucab-web/Controllers/AllProvidersRegisteredController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using UCABPagaloTodoMS.Application.Responses;
using UCABPagaloTodoWeb.Models;

namespace UCABPagaloTodoWeb.Controllers
{
    public class AllProvidersRegisteredController : Controller
    {
        private HttpClient _httpClient;

        public AllProvidersRegisteredController() 
        {
            _httpClient = new HttpClient();
        }

        [HttpGet]
        public async Task<IActionResult> AllProvidersRegisteredView()
        {
            var apiUrl = "https://localhost:44339/api/userquery/allproviders";
            var response = await _httpClient.GetAsync(apiUrl);
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var people = JsonConvert.DeserializeObject<List<AllUserQueryResponse>>(responseContent);
                var users = MapAllUsersResponseToModel(people);
                return View("~/Views/Administration/AllProvidersRegisteredView.cshtml", users);

            }

            return View("~/Views/Home/AccessDeniedView");
        }

        public List<AllUsersViewModel> MapAllUsersResponseToModel(List<AllUserQueryResponse> response)
        {
            // Crear una lista para almacenar los objetos mapeados
            var usersViewModel = new List<AllUsersViewModel>();

            // Recorrer cada objeto en la lista original y crear un nuevo objeto mapeado
            foreach (var userQueryResponse in response)
            {
                var userViewModel = new AllUsersViewModel
                {
                    Dni = userQueryResponse.Dni,
                    Name = userQueryResponse.Name,
                    Lastname = userQueryResponse.Lastname,
                    Username = userQueryResponse.Username,
                    Email = userQueryResponse.Email,
                    PhoneNumber = userQueryResponse.PhoneNumber
                };
                usersViewModel.Add(userViewModel);
            }
            return usersViewModel;
        }
    }
}

src/pagalotodo-ucab-web/Controllers/AllServicesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UCABPagaloTodoWeb.Models;
using System.Net.Http;
using Newtonsoft.Json;
using UCABPagaloTodoMS.Application.Responses;
using System.Text;

namespace UCABPagaloTodoWeb.Controllers
{
    public class AllServicesController : Controller
    {
        private HttpClient _httpClient;

        public AllServicesController()
        {
            _httpClient = new HttpClient();
        }
        [HttpGet]
        public async Task<IActionResult> AllServicesView()
        {
            var apiUrl = "https://localhost:44339/api/servicequery/allservices";
            var response = await _httpClient.GetAsync(apiUrl);
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var Response = JsonConvert.DeserializeObject<List<AllServicesQueryResponse>>(responseContent);

                var services = MapAllServicesResponseToModel(Response);


                return View("~/Views/Administration/AllServicesView.cshtml", services);
            }
            return View("~/Views/Home/AccessDeniedView.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> AllServicesView(string id)
        {
            string serviceId = id;
            var apiUrl = "https://localhost:44339/api/servicequery/byguid?id=";
            var url = apiUrl + serviceId;
            var response = await _httpClient.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var Response = JsonConvert.DeserializeObject<OneServiceResponse>(responseContent);

                var model = new UpdateServiceViewModel
                {
                    ServiceName = Response.ServiceName,
                    TypeService = Response.TyperService,
                    ContactNumber = Response.ContactNumber,
                    Username = Response.ProviderUsername
                };
                return View("~/Views/Service/UpdateServiceView.cshtml", model);
            }
            return View("~/Views/Home/AccessDeniedView");
        }

        public List<AllServicesViewModel> MapAllServicesResponseToModel(List<AllServicesQueryResponse> response)
        {
            // Crear una lista para almacenar los objetos mapeados
            var allUsersViewModel = new AllServicesViewModel();
            var usersViewModel = new List<AllServicesViewModel>();

            // Recorrer cada objeto en la lista original y crear un nuevo objeto mapeado
            foreach (var userQueryResponse in response)
            {
                var userViewModel = new AllServicesViewModel
                {
                    ServiceId = userQueryResponse.ServiceId,
                    ServiceName = userQueryResponse.ServiceName,
                    TypeService = userQueryResponse.TyperService,
                    ContactNumber = userQueryResponse.ContactNumber,
                    ProviderUsername = userQueryResponse.ProviderUsername,
                    CompanyName = userQueryResponse.CompanyName
                };
                usersViewModel.Add(userViewModel);
            }
            return usersViewModel;
        }
    }
}

src/pagalotodo-ucab-web/Controllers/ChangeUserStatusController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using UCABPagaloTodoMS.Application.Responses;
using UCABPagaloTodoWeb.Models;

namespace UCABPagaloTodoWeb.Controllers
{
    public class ChangeUserStatusController : Controller
    {
        private readonly ILogger<ChangeUserStatusController> _logger;
        private HttpClient _httpClient;

        public ChangeUserStatusController(ILogger<ChangeUserStatusController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }

        public async Task<IActionResult> ChangeUserStatusView(string username)
        {
            var apiUrl = "https://localhost:44339/api/userquery/byusername?username=";
            var url = apiUrl + username;
            var response = await _httpClient.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<OneUserResponse>(responseContent);

                ChangeUserStatusViewModel model = new ChangeUserStatusViewModel
                {
                    Username = loginResponse.Username,
                    Status = loginResponse.Status                    
                };
                return View("~/Views/Administration/ChangeUserStatusView.cshtml",model);
            }

            return RedirectToAction("AccessDeniedView", "Home");
        }
        [HttpPost]
        public async Task<IActionResult> ChangeUserStatusViewAction(string _username, bool estado)
        {
            var apiUrl = "https://localhost:44339/api/userupdate/changeuserstatus";
            var requestBody = new { username = _username, status = estado };
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<ChangeUserStatusResponse>(responseContent);
                return RedirectToAction("AllUsersView","Admin");

            }
            return View("~/Views/Administration/AdminHomeView.cshtml");
        }



    }
}

src/pagalotodo-ucab-web/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UCABPagaloTodoWeb.Models;
using System.Net.Http;
using Newtonsoft.Json;
using UCABPagaloTodoMS.Application.Responses;
using System.Text;
using System.Reflection;

namespace UCABPagaloTodoWeb.Controllers
{
    public class ServiceController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private HttpClient _httpClient;

        public ServiceController(ILogger<AdminController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }

        public IActionResult AddServiceView() 
        {
            AddServiceViewModel model = new AddServiceViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddServiceAction(AddServiceViewModel service) {
            var apiUrl = "https://localhost:44339/api/addservice/addservice";
            var requestBody = new
            { 
                serviceName =  service.ServiceName,
                typeService = service.TypeService,
                contactNumber = service.ContactNumber,
                userName = service.UserName
            };
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));
            // Envía la solicitud POST con el body en formato JSON
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                return View("~/Views/Administration/AdminServiceView.cshtml");
            }

                return View("~/Views/Administration/AdminHomeView.cshtml");
        }

        public async Task<IActionResult> UpdateServiceView(string id)
        {
            //Ojito pelao aqui, cambiar
            string ServiceGuid = id;
            var apiUrl = "https://localhost:44339/api/servicequery/byguid?id="; 
            var url = apiUrl + ServiceGuid;
            var response = await _httpClient.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<ServiceUpdateResponse>(responseContent);

                UpdateServiceViewModel model = new UpdateServiceViewModel
                {
                    ServiceName = loginResponse.ServiceName,
                    ContactNumber = loginResponse.ContactNumber,
                    TypeService = loginResponse.TypeService
                };
                return View(model);
            }

            return RedirectToAction("AccessDeniedView", "Home");
        }

        public async Task<IActionResult> DeleteServiceView(string ServiceName, string Provider)
        {
            var apiUrl = "https://localhost:44339/api/servicequery/byservicename";
            var requestBody = new 
            { 
                ServiceName = ServiceName, 
                ProviderUserName = Provider 
            };

            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var service = JsonConvert.DeserializeObject<OneServiceResponse>(responseContent);
                var model = new DeleteServiceViewModel
                {
                    ServiceName = service.ServiceName,
                    Provider = service.ProviderUsername
                };

                return View(model);
            }

            return RedirectToAction("AccessDeniedView", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteService(string ServiceName, string Provider)
        {
            var apiUrl = "https://localhost:44339/api/servicedelete/deleteservice";
            var requestBody = new
            {
                ServiceName = ServiceName,
                UserName = Provider
            };

            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var serviceList = JsonConvert.DeserializeObject<ServiceDeleteResponse>(responseContent);

                return View("~/Views/Administration/AdminHomeView.cshtml");
            }

            return View("~/Views/Home/AccessDeniedView.cshtml");
        }
    }
}

src/pagalotodo-ucab-web/Views/Administration/AdminHomeView.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Welcome de admin</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/pagalotodo-ucab-web/Views/Administration/AdminServiceView.cshtml
@{
    ViewData["Tittle"] = "AdminService Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Administracion de servicios</h1>

    <form asp-controller="Service" asp-action="AddServiceView" >
        <button type="submit" class="btn btn-primary">Agregar Servicio</button>
    </form>

    <form asp-controller="AllServices" asp-action="AllServicesView" method="get">
        <button type="submit" class="btn btn-secondary">Actualizar o Eliminar Servicios</button>
    </form>


</div>

src/pagalotodo-ucab-web/Views/Administration/AllProvidersRegisteredView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    ViewData["Tittle"] = "AdminUser Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model IEnumerable<AllUsersViewModel>

<h1>Listado de usuarios</h1>

<style>
    .user-table {
        border-collapse: collapse;
    }

        .user-table th, .user-table td {
            padding: 10px;
            border: 1px solid #ccc;
        }
</style>

<table class="user-table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Username</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Dni</td>
                <td>@user.Name</td>
                <td>@user.Username</td>
            </tr>
        }
    </tbody>
</table>

src/pagalotodo-ucab-web/Views/Administration/AllServicesView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<AllServicesViewModel>
@{
    ViewData["Tittle"] = "AdminServices Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Listado de Servicios</h1>

<style>
    .user-table {
        border-collapse: collapse;
    }

        .user-table th, .user-table td {
            padding: 10px;
            border: 1px solid #ccc;
        }
</style>

<table class="user-table">
    <thead>
        <tr>
            <th>Nombre Servicio</th>
            <th>Tipo</th>
            <th>Proveedor</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.ServiceName</td>
                <td>@user.TypeService</td>
                <td>@user.ProviderUsername</td>
                <td>
                    <form action="/UpdateService/UpdateServiceAction" method="post">

                        <input type="hidden" name="id" value="@user.ServiceId" />
                        <button type="submit" asp-route-id="@user.ServiceId">Editar</button>
                    </form>
                    <a href="/Service/DeleteServiceView?ServiceName=@user.ServiceName&provider=@user.ProviderUsername">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/pagalotodo-ucab-web/Views/Administration/AllUsersView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Tittle"] = "AdminUser Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model IEnumerable<AllUsersViewModel>

<h1>Listado de usuarios</h1>

<style>
    .user-table {
        border-collapse: collapse;
    }

        .user-table th, .user-table td {
            padding: 10px;
            border: 1px solid #ccc;
        }
</style>

<table class="user-table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Username</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Dni</td>
                <td>@user.Name</td>
                <td>@user.Username</td>
                <td>
                    <form action="/Admin/UpdateUserViewAdmin" method="post">
                        
                        <input type="hidden" name="username" value="@user.Username" />
                        <button type="submit" asp-route-username="@user.Username">Editar</button>
                    </form>
                    <a href="/ChangeUserStatus/ChangeUserStatusView?username=@user.Username">Cambiar Estado</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/pagalotodo-ucab-web/Views/Administration/ChangeUserStatusView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model UCABPagaloTodoWeb.Models.ChangeUserStatusViewModel
@{
    ViewData["Title"] = "Cambiar Estado de Usuario";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post" action="/ChangeUserStatus/ChangeUserStatusViewAction">
    <input type="hidden" name="_username" value="@Model.Username" />
    <label for="estado">Estado:</label>
    <select name="estado" id="estado">
        <option value="true" selected="@((Model.Status.HasValue && Model.Status.Value) ? "true" : null)">Activo</option>
        <option value="false" selected="@((Model.Status.HasValue && !Model.Status.Value) ? "true" : null)">Inactivo</option>
    </select>
    <div>
        Nombre de usuario: @Model.Username
    </div>
    <button type="submit">Guardar</button>
</form>