src/pagalotodo-ucab-web/Models/AddServiceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace UCABPagaloTodoWeb.Models
{
    public class AddServiceViewModel
    {
        [Required(ErrorMessage = "Introduzca el nombre del servicio")]
        public string? ServiceName { get; set; }

        [Required(ErrorMessage = "Introduzca el tipo de servicio")]
        public string? TypeService { get; set; }

        [RegularExpression(@"^[0-9]*$", ErrorMessage = "El número de teléfono debe ser un valor numérico.")]
        [StringLength(15, MinimumLength = 11, ErrorMessage = "La longitud del número de teléfono debe estar entre 11 y 15 caracteres.")]
        public string? ContactNumber { get; set; }

        [Required(ErrorMessage = "Introduzca su usuario")]
        public string? UserName { get; set; }
    }
}

src/pagalotodo-ucab-web/Models/DeleteServiceViewModel.cs
namespace UCABPagaloTodoWeb.Models
{
    public class DeleteServiceViewModel
    {
        public string? ServiceName { get; set; }
        public string? Provider { get; set;}
    }
}

src/pagalotodo-ucab-web/Models/UpdateServiceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace UCABPagaloTodoWeb.Models
{
    public class UpdateServiceViewModel
    {
        public string ServiceName { get; set; }

        public string? TypeService { get; set; }

        [RegularExpression(@"^[0-9]*$", ErrorMessage = "El número de teléfono debe ser un valor numérico.")]
        [StringLength(15, MinimumLength = 11, ErrorMessage = "La longitud del número de teléfono debe estar entre 11 y 15 caracteres.")]
        public string? ContactNumber { get; set; }

        public string? Username { get; set; }


        public UpdateServiceViewModel()
        {
            ServiceName = "";
            TypeService = "";
            ContactNumber = "";
        }
    }
}

src/pagalotodo-ucab-web/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Diagnostics;
using System.Net.Http;
using UCABPagaloTodoMS.Application.Responses;
using UCABPagaloTodoWeb.Models;


namespace UCABPagaloTodoWeb.Controllers
{
    public class AdminController : Controller 
    {
        private readonly ILogger<AdminController> _logger;
        private HttpClient _httpClient;

        public AdminController(ILogger<AdminController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();

        }

        public IActionResult AdminHomeView()
        {
            return View("~/Views/Administration/AdminHomeView.cshtml");
        }

        public IActionResult AdminUserView()
        {
            return View("~/Views/Administration/AdminUserView.cshtml");
        }

        public IActionResult AdminServiceView()
        {
            return View("~/Views/Administration/AdminServiceView.cshtml");
        }

        [HttpGet]
        public async Task<IActionResult> AllUsersView()
        {
            var apiUrl = "https://localhost:44339/api/userquery/allusers";
            var response = await _httpClient.GetAsync(apiUrl);
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var people = JsonConvert.DeserializeObject<List<AllUserQueryResponse>>(responseContent);
                var users = MapAllUsersResponseToModel(people);
                return View("~/Views/Administration/AllUsersView.cshtml", users);

            }

            return View("~/Views/Home/AccessDeniedView");
        }


        [HttpPost]
        //Por alguna EXTRAÑA RAZON el metodo se debe llamar igual al de arriba arriba AllUsersView, A PESAR QUE EN LA VISTA A LA HORA DE DAR AL BOTON EDITAR deberia ejecutarse el metodo
        //UpdateUsersViewAdmin, pero no, NO LO HACE Y NO PREGUNTES PQ
        public async Task<IActionResult> AllUsersView(string username) //redirige a UpdateUser
        {
            string userName = username;
            var apiUrl = "https://localhost:44339/api/userquery/byusername?username=";
            var url = apiUrl + userName;
            var response = await _httpClient.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var Response = JsonConvert.DeserializeObject<OneUserResponse>(responseContent);

                UpdateUserViewModel model = new UpdateUserViewModel
                {
                    Name = Response.Name,
                    Lastname = Response.Lastname,
                    UserName = Response.Username,
                    Email = Response.Email,
                    PhoneNumber = Response.PhoneNumber
                };
                return View("~/Views/User/UpdateUserView.cshtml", model);
            }

            return RedirectToAction("AccessDeniedView", "Home");
        }


        public List<AllUsersViewModel> MapAllUsersResponseToModel(List<AllUserQueryResponse> response)
        {
            // Crear una lista para almacenar los objetos mapeados
            var usersViewModel = new List<AllUsersViewModel>();

            // Recorrer cada objeto en la lista original y crear un nuevo objeto mapeado
            foreach (var userQueryResponse in response)
            {
                var userViewModel = new AllUsersViewModel
                {
                    Dni = userQueryResponse.Dni,
                    Name = userQueryResponse.Name,
                    Lastname = userQueryResponse.Lastname,
                    Username = userQueryResponse.Username,
                    Email = userQueryResponse.Email,
                    PhoneNumber = userQueryResponse.PhoneNumber
                };
                usersViewModel.Add(userViewModel);
            }
            return usersViewModel;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/pagalotodo-ucab-web/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UCABPagaloTodoWeb.Models;
using System.Net.Http;
using Newtonsoft.Json;
using UCABPagaloTodoMS.Application.Responses;
using System.Text;
using System.Reflection;

namespace UCABPagaloTodoWeb.Controllers
{
    public class ServiceController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private HttpClient _httpClient;

        public ServiceController(ILogger<AdminController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }

        public IActionResult AddServiceView() 
        {
            AddServiceViewModel model = new AddServiceViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddServiceAction(AddServiceViewModel service) {
            var apiUrl = "https://localhost:44339/api/addservice/addservice";
            var requestBody = new
            { 
                serviceName =  service.ServiceName,
                typeService = service.TypeService,
                contactNumber = service.ContactNumber,
                userName = service.UserName
            };
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));
            // Envía la solicitud POST con el body en formato JSON
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                return View("~/Views/Administration/AdminServiceView.cshtml");
            }

                return View("~/Views/Administration/AdminHomeView.cshtml");
        }

        public async Task<IActionResult> UpdateServiceView(string id)
        {
            //Ojito pelao aqui, cambiar
            string ServiceGuid = id;
            var apiUrl = "https://localhost:44339/api/servicequery/byguid?id="; 
            var url = apiUrl + ServiceGuid;
            var response = await _httpClient.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<ServiceUpdateResponse>(responseContent);

                UpdateServiceViewModel model = new UpdateServiceViewModel
                {
                    ServiceName = loginResponse.ServiceName,
                    ContactNumber = loginResponse.ContactNumber,
                    TypeService = loginResponse.TypeService
                };
                return View(model);
            }

            return RedirectToAction("AccessDeniedView", "Home");
        }

        public async Task<IActionResult> DeleteServiceView(string ServiceName, string Provider)
        {
            var apiUrl = "https://localhost:44339/api/servicequery/byservicename";
            var requestBody = new 
            { 
                ServiceName = ServiceName, 
                ProviderUserName = Provider 
            };

            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var service = JsonConvert.DeserializeObject<OneServiceResponse>(responseContent);
                var model = new DeleteServiceViewModel
                {
                    ServiceName = service.ServiceName,
                    Provider = service.ProviderUsername
                };

                return View(model);
            }

            return RedirectToAction("AccessDeniedView", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteService(string ServiceName, string Provider)
        {
            var apiUrl = "https://localhost:44339/api/servicedelete/deleteservice";
            var requestBody = new
            {
                ServiceName = ServiceName,
                UserName = Provider
            };

            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var serviceList = JsonConvert.DeserializeObject<ServiceDeleteResponse>(responseContent);

                return View("~/Views/Administration/AdminHomeView.cshtml");
            }

            return View("~/Views/Home/AccessDeniedView.cshtml");
        }
    }
}

src/pagalotodo-ucab-web/Controllers/UpdateServiceController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using UCABPagaloTodoMS.Application.Responses;
using UCABPagaloTodoWeb.Models;

namespace UCABPagaloTodoWeb.Controllers
{
    public class UpdateServiceController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private HttpClient _httpClient;

        public UpdateServiceController(ILogger<AdminController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateServiceAction(UpdateServiceViewModel _model)
        {
            var apiUrl = "https://localhost:44339/api/serviceupdate/updateservice";
            var requestBody = new 
            { 
                serviceName = _model.ServiceName,
                typeService = _model.TypeService,
                contactNumber = _model.ContactNumber,
                userName = _model.Username
            };
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));
            // Envía la solicitud POST con el body en formato JSON
            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var loginResponse = JsonConvert.DeserializeObject<ServiceUpdateResponse>(responseContent);

                return RedirectToAction("AllServicesView", "AllServices");
            }

            return RedirectToAction("AccessDeniedView", "Home");
        }
    }
}

src/pagalotodo-ucab-web/Views/Service/AddServiceView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model UCABPagaloTodoWeb.Models.AddServiceViewModel
@{
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

<div class="col-md-12 col-sm-12">
    <div class="contenedorlogin">
        <form asp-action="AddServiceAction" asp-controller="Service" method="post">
            <div class="form-group">
                <label>Nombre del servicio</label>
                <input type="text" name="ServiceName" class="form-control" placeholder="Nombre del servicio" data-val="true" data-val-required="El campo Nombre del servicio es requerido">
                @Html.ValidationMessageFor(m => m.ServiceName, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Tipo de servicio</label>
                <input type="text" name="TypeService" class="form-control" placeholder="Tipo de servicio" data-val="true" data-val-required="El campo Tipo de servicio es requerido">
                @Html.ValidationMessageFor(m => m.TypeService, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Número de contacto</label>
                <input type="text" name="ContactNumber" class="form-control" placeholder="Número de contacto" data-val="true" 
                    data-val-regex-pattern="^[0-9]*$" data-val-regex="El número de teléfono debe ser un valor numérico." 
                    data-val-length-min="11" data-val-length-max="15" data-val-length="La longitud del número de teléfono debe estar entre 11 y 15 caracteres.">
                @Html.ValidationMessageFor(m => m.ContactNumber, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Nombre de usuario del Proveedor</label>
                <input type="text" name="UserName" class="form-control" placeholder="Nombre de usuario" data-val="true" data-val-required="El campo Nombre de usuario es requerido">
                @Html.ValidationMessageFor(m => m.UserName, null, new { @class = "text-danger" })
            </div>
            <div class="botones">
                <button type="submit" class="btn btn-success">Registrar servicio</button>
                <a class="btn btn-danger" asp-area="" asp-controller="Admin" asp-action="AdminHomeView">Cancelar</a>
            </div>
        </form>
    </div>
</div>

src/pagalotodo-ucab-web/Views/Service/AllServicesToPayView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<AllServicesViewModel>
@{
    ViewData["Tittle"] = "AdminServices Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listado de Servicios</h1>

<style>
    .user-table {
        border-collapse: collapse;
    }

        .user-table th, .user-table td {
            padding: 10px;
            border: 1px solid #ccc;
        }
</style>

<table class="user-table">
    <thead>
        <tr>
            <th>Nombre Servicio</th>
            <th>Tipo</th>
            <th>Proveedor</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.ServiceName</td>
                <td>@user.TypeService</td>
                <td>@user.ProviderUsername</td>
                <td>
                    <form action="/AddPayment/AddPaymentView" method="post">

                        <input type="hidden" name="id" value="@user.ServiceId" />
                        <button type="submit" asp-route-id="@user.ServiceId">Pagar</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

src/pagalotodo-ucab-web/Views/Service/DeleteServiceView.cshtml
@{
    Layout = null;
}
@model UCABPagaloTodoWeb.Models.DeleteServiceViewModel

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<div class="col-md-12 col-sm-12">
    <div class="col-md-4">
        <h1>Eliminar Servicio</h1>
        <p>¿Estás seguro que deseas eliminar el servicio @Model.ServiceName?</p>
        <form asp-action="DeleteService" asp-controller="Service" method="post">
            <div class="form-group">
                <label>Service Name:</label>
                <p>@Model.ServiceName</p>
                <input type="hidden" name="ServiceName" value="@Model.ServiceName" />
            </div>
            <div class="form-group">
                <label>Provider:</label>
                <p>@Model.Provider</p>
                <input type="hidden" name="Provider" value="@Model.Provider" />
            </div>
            <div class="botones">
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a class="btn btn-default" asp-area="" asp-controller="Admin" asp-action="AdminHomeView">Cancelar</a>
            </div>
        </form>
        <p>@ViewBag.Error</p>
    </div>
</div>

src/pagalotodo-ucab-web/Views/Service/NoPaymentOptionsOnService.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Login Invalido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">El servicio no tiene metodos de pago disponibles</h1>
    <p>Ingrese de nuevo a la pestaña de pagos si lo desea</p>
</div>

src/pagalotodo-ucab-web/Views/Service/UpdateServiceView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model UCABPagaloTodoWeb.Models.UpdateServiceViewModel
@{
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");    
    }
    }

<div class="col-md-12 col-sm-12">
    <div class="col-md-4">
        <form asp-action="UpdateServiceAction" asp-controller="UpdateService" method="post">
            <input type="hidden" name="Username" value="@Model.Username">
            <div class="form-group">
                <label>Nombre del Servicio</label>
                <input type="text" name="ServiceName" class="form-control" placeholder="Servicio" value="@Model.ServiceName">
                @Html.ValidationMessageFor(m => m.ServiceName ,null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Tipo de Servicio</label>
                <input type="text" name="TypeService" class="form-control" placeholder="Tipo" value="@Model.TypeService">
                @Html.ValidationMessageFor(m => m.TypeService ,null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Número de Contacto1</label>
                <input type="text" name="ContactNumber" class="form-control" placeholder="Número" value="@Model.ContactNumber"
                    data-val-regex-pattern="^[0-9]*$" data-val-regex="El número de teléfono debe ser un valor numérico." data-val-length-min="11" data-val-length-max="15"
                    data-val-length="La longitud del número de teléfono debe estar entre 11 y 15 caracteres.">
                @Html.ValidationMessageFor(m => m.ContactNumber ,null, new { @class = "text-danger" })
            </div>
            <div class="botones">
                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                <a class="btn btn-danger" asp-area="" asp-controller="Admin" asp-action="AdminHomeView">Cancelar</a>
            </div>
        </form>
        <p>@ViewBag.Error</p>
    </div>
</div>