src/pagalotodo-ucab-web/Models/AddPaymentContractViewModel.cs
using UCABPagaloTodoMS.Application.Responses;

namespace UCABPagaloTodoWeb.Models
{
    public class AddPaymentContractViewModel
    {
        public Guid ServiceId { get; set; }
        public string? ServiceName { get; set; }
        public Guid UserId { get; set; }
        public List<PaymentOptionsByServiceIdResponse>? PaymentOption { get; set; }
        public string? ContractNumber { get; set; }
        public double? Amount { get; set; }
        public DateTime Date { get; set; }
    }
}

src/pagalotodo-ucab-web/Models/AddPaymentPhonesViewModel.cs
using UCABPagaloTodoMS.Application.Responses;

namespace UCABPagaloTodoWeb.Models
{
    public class AddPaymentPhonesViewModel
    {
        public Guid ServiceId { get; set; }
        public string? ServiceName { get; set; }
        public Guid UserId { get; set; }
        public List<PaymentOptionsByServiceIdResponse>? PaymentOption { get; set; }
        public string? PhoneNumber { get; set; }
        public double? Amount { get; set; }
        public DateTime Date { get; set; }
    }
}

src/pagalotodo-ucab-web/Controllers/AddPaymentController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using UCABPagaloTodoMS.Application.Responses;
using UCABPagaloTodoWeb.Models;

namespace UCABPagaloTodoWeb.Controllers
{
    public class AddPaymentController : Controller
    {
        private readonly ILogger<AddPaymentController> _logger;
        private HttpClient _httpClient;

        public AddPaymentController(ILogger<AddPaymentController> logger)
        {
            _logger = logger;
            _httpClient = new HttpClient();

        }

        [HttpPost]
        public async Task<IActionResult> AddPaymentContractAction(string _ServiceId, string _UserId, string _OptionId, string _ContractNumber, double _Amount)
        {
            var apiUrl = "https://localhost:44339/api/payment/addpayment";
            var requestBody = new 
            {
                contractNumber = _ContractNumber,
                phoneNumber = "",
                amount = _Amount,
                userId = _UserId,
                serviceId = _ServiceId,
                paymentOptionId = _OptionId
            };
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));

            if (response.IsSuccessStatusCode) 
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var Response = JsonConvert.DeserializeObject<AddPaymentResponse>(responseContent);

                if (Response.success == true) 
                {
                    return View("~/Views/AddPayment/PaymentSucessful.cshtml");
                }
            }

            return View("~/Views/AddPayment/PaymentFailed.cshtml");
        }

        public async Task<IActionResult> AddPaymentPhoneAction(string _ServiceId, string _UserId, string _OptionId, string _PhoneNumber, double _Amount)
        {
            var apiUrl = "https://localhost:44339/api/payment/addpayment";
            var requestBody = new
            {
                contractNumber = "",
                phoneNumber = _PhoneNumber,
                amount = _Amount,
                userId = _UserId,
                serviceId = _ServiceId,
                paymentOptionId = _OptionId
            };
            var jsonBody = JsonConvert.SerializeObject(requestBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            }); // Serializa el body a formato JSON
            var response = await _httpClient.PostAsync(apiUrl, new StringContent(jsonBody, Encoding.UTF8, "application/json"));

            if (response.IsSuccessStatusCode)
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                var Response = JsonConvert.DeserializeObject<AddPaymentResponse>(responseContent);

                if (Response.success == true)
                {
                    return View("~/Views/AddPayment/PaymentSucessful.cshtml");
                }
            }

            return View("~/Views/AddPayment/PaymentFailed.cshtml");
        }
    }
}

src/pagalotodo-ucab-web/Views/AddPayment/AddPaymentContractView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Pagar Servicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model UCABPagaloTodoWeb.Models.AddPaymentContractViewModel

<form asp-action="AddPaymentContractAction" asp-controller="AddPayment" method="post">
    <div>
        <input type="hidden" id="_ServiceId" name="_ServiceId" value="@Model.ServiceId"/>
    </div>
    <div>
        <label for="serviceName">Servicio:</label>
        <input type="text" id="_ServiceName" name="_ServiceName" value="@Model.ServiceName" readonly />
    </div>
    <div>
        <input type="hidden" id="_UserId" name="_UserId" value="@Model.UserId" readonly />
    </div>
    <div>
        <label for="paymentOption">Payment Option:</label>
        <select id="_OptionId" name="_OptionId">
            @foreach (var option in Model.PaymentOption)
            {
                <option value="@option.PaymentOptionId">@option.PaymentOptionName</option>
            }
        </select>
    </div>
    <div>
        <label for="contractNumber">Contract Number:</label>
        <input type="text" id="_ContractNumber" name="_ContractNumber" />
    </div>
    <div>
        <<label for="amount">Amount:</label>
        <input type="number" id="_Amount" name="_Amount" step="0.01" />
    </div>
    <button type="submit">Add Payment</button>
</form>

src/pagalotodo-ucab-web/Views/AddPayment/AddPaymentPhoneView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Pagar Servicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model UCABPagaloTodoWeb.Models.AddPaymentPhonesViewModel

<form asp-action="AddPaymentPhoneAction" asp-controller="AddPayment" method="post">
    <div>
        <input type="hidden" id="_ServiceId" name="_ServiceId" value="@Model.ServiceId" />
    </div>
    <div>
        <label for="serviceName">Servicio:</label>
        <input type="text" id="_ServiceName" name="_ServiceName" value="@Model.ServiceName" readonly />
    </div>
    <div>
        <input type="hidden" id="_UserId" name="_UserId" value="@Model.UserId" readonly />
    </div>
    <div>
        <label for="paymentOption">Payment Option:</label>
        <select id="_OptionId" name="_OptionId">
            @foreach (var option in Model.PaymentOption)
            {
                <option value="@option.PaymentOptionId">@option.PaymentOptionName</option>
            }
        </select>
    </div>
    <div>
        <label for="contractNumber">Numero de telefono:</label>
        <input type="text" id="_PhoneNumber" name="_PhoneNumber" />
    </div>
    <div>
        <label for="amount">Monto a recargar:</label>
        <input type="number" id="_Amount" name="_Amount" step="0.01" />
    </div>
    <button type="submit">Add Payment</button>
</form>

src/pagalotodo-ucab-web/Views/AddPayment/PaymentFailed.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Pago Fallido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Pago Fallido</h1>
    <p>Intente nuevamente el pago</p>
</div>

src/pagalotodo-ucab-web/Views/AddPayment/PaymentSucessful.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Pago Procesado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Pago Realizado con exito</h1>
    <p>Vuelva al inicio para seguir usando el portal de pagos</p>
</div>